import { StrictMode } from "react";
import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App";
import { BrowserRouter } from "react-router-dom";
import "./assets/styles/tokens.css";
import "./assets/styles/reset.css";
import "./assets/styles/global.css";
import "./assets/styles/corporate.css";
import "./assets/styles/animations.css";
const root = document.getElementById("root")!;
const app = <StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>;
if (root.hasChildNodes()) hydrateRoot(root, app);
else createRoot(root).render(app);
